
/*
 * 
 */

package fr.unice.polytech.si._4a.isa.tcf.customer_care;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import fr.unice.polytech.isa.tcf.webservice.CustomerCareService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Mar 18 18:31:18 CET 2016
 * Generated source version: 2.2.10
 * 
 */


@WebServiceClient(name = "CustomerCareServiceImplService", 
                  wsdlLocation = "file:/home/user/DevOps/DevOps_Partie_2/modulesMaven/client/stubs/src/main/resources/CustomerCareWS.wsdl",
                  targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/customer-care") 
public class CustomerCareServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/customer-care", "CustomerCareServiceImplService");
    public final static QName CustomerCareServiceImplPort = new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/customer-care", "CustomerCareServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/user/DevOps/DevOps_Partie_2/modulesMaven/client/stubs/src/main/resources/CustomerCareWS.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/home/user/DevOps/DevOps_Partie_2/modulesMaven/client/stubs/src/main/resources/CustomerCareWS.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CustomerCareServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerCareServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerCareServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CustomerCareServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public CustomerCareServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerCareServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerCareService
     */
    @WebEndpoint(name = "CustomerCareServiceImplPort")
    public CustomerCareService getCustomerCareServiceImplPort() {
        return super.getPort(CustomerCareServiceImplPort, CustomerCareService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerCareService
     */
    @WebEndpoint(name = "CustomerCareServiceImplPort")
    public CustomerCareService getCustomerCareServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CustomerCareServiceImplPort, CustomerCareService.class, features);
    }

}
