
/*
 * 
 */

package fr.unice.polytech.si._4a.isa.tcf.cart;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import fr.unice.polytech.isa.tcf.webservice.CartWebService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Mar 18 18:31:18 CET 2016
 * Generated source version: 2.2.10
 * 
 */


@WebServiceClient(name = "CartWebServiceImplService", 
                  wsdlLocation = "file:/home/user/DevOps/DevOps_Partie_2/modulesMaven/client/stubs/src/main/resources/CartWS.wsdl",
                  targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/cart") 
public class CartWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/cart", "CartWebServiceImplService");
    public final static QName CartWebServiceImplPort = new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/cart", "CartWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/user/DevOps/DevOps_Partie_2/modulesMaven/client/stubs/src/main/resources/CartWS.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/home/user/DevOps/DevOps_Partie_2/modulesMaven/client/stubs/src/main/resources/CartWS.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CartWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CartWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CartWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CartWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public CartWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CartWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CartWebService
     */
    @WebEndpoint(name = "CartWebServiceImplPort")
    public CartWebService getCartWebServiceImplPort() {
        return super.getPort(CartWebServiceImplPort, CartWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CartWebService
     */
    @WebEndpoint(name = "CartWebServiceImplPort")
    public CartWebService getCartWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CartWebServiceImplPort, CartWebService.class, features);
    }

}
