
package fr.unice.polytech.isa.tcf.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.10
 * Thu Mar 24 15:04:35 CET 2016
 * Generated source version: 2.2.10
 * 
 */

@WebFault(name = "AlreadyExistingCustomerException", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/")
public class AlreadyExistingCustomerException_Exception extends Exception {
    public static final long serialVersionUID = 20160324150435L;
    
    private fr.unice.polytech.isa.tcf.webservice.AlreadyExistingCustomerException alreadyExistingCustomerException;

    public AlreadyExistingCustomerException_Exception() {
        super();
    }
    
    public AlreadyExistingCustomerException_Exception(String message) {
        super(message);
    }
    
    public AlreadyExistingCustomerException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AlreadyExistingCustomerException_Exception(String message, fr.unice.polytech.isa.tcf.webservice.AlreadyExistingCustomerException alreadyExistingCustomerException) {
        super(message);
        this.alreadyExistingCustomerException = alreadyExistingCustomerException;
    }

    public AlreadyExistingCustomerException_Exception(String message, fr.unice.polytech.isa.tcf.webservice.AlreadyExistingCustomerException alreadyExistingCustomerException, Throwable cause) {
        super(message, cause);
        this.alreadyExistingCustomerException = alreadyExistingCustomerException;
    }

    public fr.unice.polytech.isa.tcf.webservice.AlreadyExistingCustomerException getFaultInfo() {
        return this.alreadyExistingCustomerException;
    }
}
