package fr.unice.polytech.isa.tcf.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Mar 18 18:31:18 CET 2016
 * Generated source version: 2.2.10
 * 
 */
 
@WebService(targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", name = "CartWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface CartWebService {

    @WebMethod
    @RequestWrapper(localName = "getCustomerCartContents", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "fr.unice.polytech.isa.tcf.webservice.GetCustomerCartContents")
    @ResponseWrapper(localName = "getCustomerCartContentsResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "fr.unice.polytech.isa.tcf.webservice.GetCustomerCartContentsResponse")
    @WebResult(name = "cart_contents", targetNamespace = "")
    public java.util.List<fr.unice.polytech.isa.tcf.webservice.Item> getCustomerCartContents(
        @WebParam(name = "customer_name", targetNamespace = "")
        java.lang.String customerName
    ) throws UnknownCustomerException_Exception;

    @WebMethod
    @RequestWrapper(localName = "removeItemToCustomerCart", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "fr.unice.polytech.isa.tcf.webservice.RemoveItemToCustomerCart")
    @ResponseWrapper(localName = "removeItemToCustomerCartResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "fr.unice.polytech.isa.tcf.webservice.RemoveItemToCustomerCartResponse")
    public void removeItemToCustomerCart(
        @WebParam(name = "customer_name", targetNamespace = "")
        java.lang.String customerName,
        @WebParam(name = "item", targetNamespace = "")
        fr.unice.polytech.isa.tcf.webservice.Item item
    ) throws UnknownCustomerException_Exception;

    @WebMethod
    @RequestWrapper(localName = "addItemToCustomerCart", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "fr.unice.polytech.isa.tcf.webservice.AddItemToCustomerCart")
    @ResponseWrapper(localName = "addItemToCustomerCartResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "fr.unice.polytech.isa.tcf.webservice.AddItemToCustomerCartResponse")
    public void addItemToCustomerCart(
        @WebParam(name = "customer_name", targetNamespace = "")
        java.lang.String customerName,
        @WebParam(name = "item", targetNamespace = "")
        fr.unice.polytech.isa.tcf.webservice.Item item
    ) throws UnknownCustomerException_Exception;

    @WebMethod
    @RequestWrapper(localName = "validate", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "fr.unice.polytech.isa.tcf.webservice.Validate")
    @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "fr.unice.polytech.isa.tcf.webservice.ValidateResponse")
    @WebResult(name = "order_id", targetNamespace = "")
    public java.lang.String validate(
        @WebParam(name = "customer_name", targetNamespace = "")
        java.lang.String customerName
    ) throws PaymentException_Exception, UnknownCustomerException_Exception;
}
