package fr.unice.polytech.isa.tcf.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.10
 * Thu Mar 24 15:04:35 CET 2016
 * Generated source version: 2.2.10
 * 
 */
 
@WebService(targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", name = "CustomerCareService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerCareService {

    @WebMethod
    @RequestWrapper(localName = "track", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "fr.unice.polytech.isa.tcf.webservice.Track")
    @ResponseWrapper(localName = "trackResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "fr.unice.polytech.isa.tcf.webservice.TrackResponse")
    @WebResult(name = "status", targetNamespace = "")
    public fr.unice.polytech.isa.tcf.webservice.OrderStatus track(
        @WebParam(name = "order_id", targetNamespace = "")
        java.lang.String orderId
    ) throws UnknownOrderId_Exception;

    @WebMethod
    @RequestWrapper(localName = "listAllRecipes", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "fr.unice.polytech.isa.tcf.webservice.ListAllRecipes")
    @ResponseWrapper(localName = "listAllRecipesResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "fr.unice.polytech.isa.tcf.webservice.ListAllRecipesResponse")
    @WebResult(name = "recipes", targetNamespace = "")
    public java.util.List<fr.unice.polytech.isa.tcf.webservice.Cookies> listAllRecipes();

    @WebMethod
    @RequestWrapper(localName = "register", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "fr.unice.polytech.isa.tcf.webservice.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "fr.unice.polytech.isa.tcf.webservice.RegisterResponse")
    public void register(
        @WebParam(name = "customer_name", targetNamespace = "")
        java.lang.String customerName,
        @WebParam(name = "credit_card_number", targetNamespace = "")
        java.lang.String creditCardNumber
    ) throws AlreadyExistingCustomerException_Exception;
}
