
package fr.unice.polytech.isa.tcf.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Mar 18 18:31:18 CET 2016
 * Generated source version: 2.2.10
 * 
 */

@WebFault(name = "PaymentException", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/")
public class PaymentException_Exception extends Exception {
    public static final long serialVersionUID = 20160318183118L;
    
    private fr.unice.polytech.isa.tcf.webservice.PaymentException paymentException;

    public PaymentException_Exception() {
        super();
    }
    
    public PaymentException_Exception(String message) {
        super(message);
    }
    
    public PaymentException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PaymentException_Exception(String message, fr.unice.polytech.isa.tcf.webservice.PaymentException paymentException) {
        super(message);
        this.paymentException = paymentException;
    }

    public PaymentException_Exception(String message, fr.unice.polytech.isa.tcf.webservice.PaymentException paymentException, Throwable cause) {
        super(message, cause);
        this.paymentException = paymentException;
    }

    public fr.unice.polytech.isa.tcf.webservice.PaymentException getFaultInfo() {
        return this.paymentException;
    }
}
