
package fr.unice.polytech.isa.tcf.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.10
 * Thu Mar 24 15:04:35 CET 2016
 * Generated source version: 2.2.10
 * 
 */

@WebFault(name = "UnknownCustomerException", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/")
public class UnknownCustomerException_Exception extends Exception {
    public static final long serialVersionUID = 20160324150435L;
    
    private fr.unice.polytech.isa.tcf.webservice.UnknownCustomerException unknownCustomerException;

    public UnknownCustomerException_Exception() {
        super();
    }
    
    public UnknownCustomerException_Exception(String message) {
        super(message);
    }
    
    public UnknownCustomerException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownCustomerException_Exception(String message, fr.unice.polytech.isa.tcf.webservice.UnknownCustomerException unknownCustomerException) {
        super(message);
        this.unknownCustomerException = unknownCustomerException;
    }

    public UnknownCustomerException_Exception(String message, fr.unice.polytech.isa.tcf.webservice.UnknownCustomerException unknownCustomerException, Throwable cause) {
        super(message, cause);
        this.unknownCustomerException = unknownCustomerException;
    }

    public fr.unice.polytech.isa.tcf.webservice.UnknownCustomerException getFaultInfo() {
        return this.unknownCustomerException;
    }
}
